[package]
name = "salsa"
version = "0.17.0-pre.2" # CHECK salsa-macros version
authors = ["Salsa developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"

[dependencies]
arc-swap = "1.4.0"
crossbeam-utils = { version = "0.8", default-features = false }
dashmap = "5.3.4"
hashlink = "0.8.0"
indexmap = "2"
lock_api = "0.4.7"
log = "0.4.5"
parking_lot = "0.12.1"
rustc-hash = "1.0"
smallvec = "1.0.0"
oorandom = "11"
salsa-macros = { version = "0.17.0-pre.2", path = "components/salsa-macros" }

[dev-dependencies]
diff = "0.1.0"
env_logger = "0.9"
linked-hash-map = "0.5.2"
rand = "0.8"
rand_distr = "0.4.3"
test-log = "0.2.11"
insta = "1.8.0"

[workspace]
members = [
    "components/salsa-macros",
    "components/dendro-salsa",
    "components/dendro-salsa-macros",
    "examples-2022/calc",
    "examples-2022/lazy-input",
    "dendro-salsa-tests",
]
